# deployments 파일은 어떤 이미지로 컨테이너들을 몇개 관리할지 정의하는 파일
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot001dep
spec:
  selector:
    matchLabels:
      app: boot001kube
  replicas: 1
  template:
    metadata:
      labels:
        app: boot001kube
    spec:
      containers:
      - name: boot-container
        image: orlzll/onion-back2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888