apiVersion: v1
kind: Service
metadata:
  name: boot001ser
spec:
  type: NodePort
  ports:
  - port: 8888 #서비스포트
    targetPort: 8888
    protocol: TCP
    nodePort: 30001
  selector:
    app: boot001kube