server:
  port: 8888

spring:
  application:
    name: onion-hot-say-yo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(KzNm9QKE+wNTwwmbqukhme3Hwo3U32Z0+E/sXpiDZf//H2NWCSFIfRFryXuLuEh4bdLPpKzen38=)
    username: ENC(MokrFvKG4z3QMZKbKaFoLg==)
    password: ENC(jxLNrjVW/769hUg5wF8pLA==)

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
  data:
    redis:
      host: 192.168.0.31
      port: 6379

token:
  access-expiration-time: 43200000          # 12H
  refresh-expiration-time: 604800000        # 7D
  secret: ENC(HfYJiFGXMXKABAzwmXWDlA9t5M6dsK3k9l1NYtB5jPIjgZAw/ges+cMG6pKRBAK67BK9kGZjGpcJfvrFC2fAuKrjKorHmAJ3RGHPTblSvJ1gon5jV/QdvDbftXn3+9ZRJD0aikbXPAo=)  # ??? ?

deepl:
  api-key: ENC(WxTL20Up6+BkqniRBmK2fimNUmG9tiWFOeEudfSKDguSsBGks2NXyTDjhju5UqAT)


#logging:
#  level:
#    root: debug
jasypt:
  encryptor:
    bean: jasyptStringEncryptor